name: Generate Snake Game

on:
  schedule:
    # Cháº¡y má»—i 12 tiáº¿ng
    - cron: "0 */12 * * *"
  workflow_dispatch: # Cho phÃ©p cháº¡y thá»§ cÃ´ng

jobs:
  build:
    name: Generate Snake Animation
    runs-on: ubuntu-latest

    steps:
      # Step 1: Generate Snake
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: Togahmechua   # ğŸ”¹ Äá»•i thÃ nh username GitHub cá»§a báº¡n
          outputs: |
            dist/github-contribution-grid-snake.svg

      # Step 2: Push lÃªn branch "output"
      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
